version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"

  # Order database
  order-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: orders
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Inventory database
  inventory-db:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # Event broker
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"   # main service port
      - "15672:15672" # management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  order-service:
    build: ./order-service
    environment:
      - DB_URL=postgres://admin:password123@order-db:5432/orders
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - order-db
      - rabbitmq
    # No ports exposed; NGINX gateway handles routing
    deploy:
      replicas: 2


  inventory-service:
    build: ./inventory-service
    environment:
      - REDIS_HOST=inventory-db
      - REDIS_PORT=6379
      - BROKER_HOST=rabbitmq
      - BROKER_PORT=5672
    depends_on:
      - inventory-db
      - rabbitmq
    ports:
      - "5001:5001"



  gateway:
    image: nginx:alpine
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - order-service
      - inventory-service

volumes:
  pgdata:
