[project]
name = "devops-order-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "prometheus-client>=0.24.1",
]

[dependency-groups]
dev = [
    "prometheus-client>=0.24.1",
]
