global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'order_service'
    static_configs:
      - targets: ['order-service:5000']

  - job_name: 'inventory_service'
    static_configs:
      - targets: ['inventory-service:5001']

  - job_name: 'rabbitmq'
    metrics_path: /metrics
    static_configs:
      - targets: ['rabbitmq:15672']

  - job_name: 'postgres'
    metrics_path: /metrics
    static_configs:
      - targets: ['order-db:5432']

  - job_name: 'redis'
    metrics_path: /metrics
    static_configs:
      - targets: ['inventory-db:6379']
